export const langs = ['uk', 'en', 'de'];

export const headerLinks: { [key: string]: string[] } = {
  uk: ['Головна', 'Пости'],
  en: ['Home', 'Posts'],
  de: ['Home', 'Beiträge'],
};

export const links = [
  '', 'posts'
]

export const mainPage: { [key: string]: string[] } = {
  uk: ['Головна сторінка', 'Навчання ангуляру – це як спроба вставити квадратний круг у круглий отвір. Спочатку ви думаєте, "О, це не так важко", але коли починаєте розбиратися, здається, що кожен кут просто чекає, коли ви відвернете погляд, щоб перевернутися на 45 градусів. Я вирішив вивчити ангуляр, і мої друзі казали мені, що це як наука ракетної інженерії. Я питав їх, чому вони не можуть просто назвати його "гратки для математичних пригод". Але ні, це мусить бути ангуляр. Коли я вперше розпочав вивчати, в мене було багато запитань. Наприклад, чому 90 градусів – це прямий кут, але 91 градус – це вже якась космічна аномалія? Мабуть, ангуляр вирішив зробити прямий кут ексклюзивним і не приймати заміни. В кінці кінців, навчання ангуляру – це як підкорення математичного гірського верхов\'я. Але навіть якщо ви збиваєте кілька кутів на шляху, не здаютеся. Пам\'ятайте, що іноді навіть саме важке завдання може бути розважливим, особливо коли ви відкриєте для себе, що геометрія – це не тільки про кутові спроби, але і про незабутні пригоди у світі геометричних форм!'],
  en: ['Home Page', 'Learning Angular is like trying to fit a square circle into a round hole. At first, you think, "Oh, it\'s not that hard," but when you start to dig in, it seems like every angle is just waiting for you to look away to turn itself by 45 degrees. I decided to tackle Angular, and my friends told me it\'s like rocket science. I asked them, why can\'t they just call it "grids for mathematical adventures"? But no, it has to be Angular. When I first started learning, I had a lot of questions. For example, why is 90 degrees a right angle, but 91 degrees is some cosmic anomaly? Probably, Angular decided to make a right angle exclusive and not accept substitutes. In the end, learning Angular is like conquering the mathematical mountain range. But even if you knock a few angles off the path, don\'t give up. Remember that sometimes even the toughest task can be entertaining, especially when you discover that geometry is not just about angular experiments but also about unforgettable adventures in the world of geometric shapes!'],
  de: ['Startseite', 'Angular lernen ist wie der Versuch, einen quadratischen Kreis in ein rundes Loch zu stecken. Anfangs denkt man: "Oh, das ist nicht so schwer", aber wenn man anfängt, sich damit zu befassen, scheint jeder Winkel nur darauf zu warten, dass man den Blick abwendet, um sich um 45 Grad zu drehen. Ich habe beschlossen, Angular zu lernen, und meine Freunde haben mir gesagt, es sei wie Raketenwissenschaft. Ich fragte sie, warum können sie es nicht einfach "Gitter für mathematische Abenteuer" nennen? Aber nein, es muss Angular sein. Als ich anfing zu lernen, hatte ich viele Fragen. Zum Beispiel, warum sind 90 Grad ein rechter Winkel, aber 91 Grad sind eine Art kosmische Anomalie? Wahrscheinlich hat Angular beschlossen, einen rechten Winkel exklusiv zu machen und keine Alternativen zu akzeptieren. Am Ende ist das Lernen von Angular wie das Bezwingen des mathematischen Bergmassivs. Aber selbst wenn Sie unterwegs einige Winkel verlieren, geben Sie nicht auf. Denken Sie daran, dass manchmal selbst die schwierigste Aufgabe unterhaltsam sein kann, besonders wenn Sie entdecken, dass Geometrie nicht nur Experimente mit Winkeln bedeutet, sondern auch unvergessliche Abenteuer in der Welt geometrischer Formen!'],
};
